// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXSjVg_pxtAA_aYTwORB-yeYAAcpnG0vQ',
    appId: '1:5528613517:web:0762ffafc95a8fd85fe8c4',
    messagingSenderId: '5528613517',
    projectId: 'e-commerce-87d55',
    authDomain: 'e-commerce-87d55.firebaseapp.com',
    storageBucket: 'e-commerce-87d55.appspot.com',
    measurementId: 'G-DJQ9L6B5XC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT3lut1UlpvzL8aZ6eBsw6ov2ps-4yKU4',
    appId: '1:5528613517:android:a6e1823eddccadc15fe8c4',
    messagingSenderId: '5528613517',
    projectId: 'e-commerce-87d55',
    storageBucket: 'e-commerce-87d55.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxnikSOD0Lbt4gyxSNXoK8IUIcLg5xNHg',
    appId: '1:5528613517:ios:649b432628f02e6d5fe8c4',
    messagingSenderId: '5528613517',
    projectId: 'e-commerce-87d55',
    storageBucket: 'e-commerce-87d55.appspot.com',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxnikSOD0Lbt4gyxSNXoK8IUIcLg5xNHg',
    appId: '1:5528613517:ios:e881dbb12360be415fe8c4',
    messagingSenderId: '5528613517',
    projectId: 'e-commerce-87d55',
    storageBucket: 'e-commerce-87d55.appspot.com',
    iosBundleId: 'com.example.eCommerce.RunnerTests',
  );
}
